services:
  db:
    image: postgres:17.4
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: products-app
    volumes:
      - ./data:/var/lib/postgresql/data